### PR TITLE
Make prettier and lint

### PR DESCRIPTION
**Pull request by NaithanB**
- I figured out the issue on Heroku with ESLint and added it back in to the project.
- There were some new lint errors that had occurred since I removed ESLint so I also fixed them.
- For a couple of the lint bugs, I just turned off the rule in the lint config file. Those are the following rules in .eslintrc:
     - "jsx-a11y/anchor-is-valid": "off",
     - "jsx-a11y/no-static-element-interactions": "off",
     - "jsx-a11y/role-supports-aria-props": "off",
     - "no-restricted-syntax": "off"
They occurred in userlist.js and header.js. I'm happy to just leave these rules off, but if you want to see the error feel free to comment out these lines and run npm start
- Ran prettier on most of the files that I worked on. 

It would probably be good to run prettier on all of the files for consistency. Prettier will just format the code and wont change any of the functionality. I can do that if it's helpful, but if you would like to handle it yourself to double check that you like the output format, the command to run prettier on a file is "npx prettier /src/components/<your-component-here.js>"

### CODE REVIEW

**Comment by BarneyShi** [comment]
@NaithanB Wow thanks. I think it saves us time if we can run prettier once on all files in this branch.

**Comment by NaithanB** [comment]
Thanks! Yeah, makes sense to me. I ran prettier on the remaining files. Pretty sure I got everything. Let me know if you spot anything not working correctly now. Everything seems good on my end.

**Comment by tyxxxx** [comment]
Looks good!

**Review by tyxxxx — APPROVED** [review]

**Comment by NaithanB** [comment]
@BarneyShi, @parksj23, would it be okay with you if I merge this today at some point? Just want to make sure I have time to fix any deployment issues if they happen to come up. It should all be fine, but, just in case.

**Review by parksj23 — APPROVED** [review]

**Review by BarneyShi — APPROVED** [review]

**Comment by NaithanB** [comment]
Thanks!

**Pull request merged**
