### PR TITLE
Add a <Schedule /> component

### PR DESCRIPTION
**Pull request by BarneyShi**
This `<Schedule />` component would pop up after a new post has been published. 
You can select multiple home tour dates, and they'd be seen on the detail page if you click `Book a home tour!`.
Screen Shot 2021-06-18 at 9 42 15 PM
Screen Shot 2021-06-18 at 9 42 48 PM

### CODE REVIEW

**Comment by NaithanB** [comment]
Looks great! 
I get an error in the console when the scheduler opens from the main page. Do you see that too? 
scheduler_error
It looks like there are a few merge conflicts too. Are these new since merging in the ESLint stuff?

**Comment by BarneyShi** [comment]
> Looks great!
> I get an error in the console when the scheduler opens from the main page. Do you see that too?
> scheduler_error
> It looks like there are a few merge conflicts too. Are these new since merging in the ESLint stuff?

@NaithanB Thanks for spotting that. I googled, and it seems like a bootstrap issue when we use things like `Modal` or `Carousel`. I disabled `StrictMode` in index.js, and now it's fixed. Conflicts are also resolved now.

**Comment by NaithanB** [comment]
Great, that fixed it. Yeah, that looks awesome! I have the links working on my end too, so I will add the scheduled dates to the dummy post states and pass them into the detail page so we can have those pieces connected for the demo (I suppose in the actual implementation we will set the post detail component info with a get request to the server).
I just noticed there's also a few errors when I turn on the linter. Mainly just adding React to the import and adding props validation. Pretty small bugs though, so no big deal.

**Comment by NaithanB** [comment]
Haha, and I just accidentally requested myself for a review...

**Comment by BarneyShi** [comment]
@NaithanB Haha one time I accidentally closed a big feature branch. I ran eslint on my component and fixed those errors.

**Comment by NaithanB** [comment]
Cool! Yeah, I think this is good to merge.

**Review by tyxxxx — APPROVED** [review]

**Review by parksj23 — APPROVED** [review]
Looks great!!

**Pull request merged**
