### PR TITLE
finished translation

### PR DESCRIPTION
**Pull request by tyxxxx**
Finished

### CODE REVIEW

**Review by BarneyShi — APPROVED** [review]
Good job! I think it looks great.

**Review by parksj23 — APPROVED** [review]
Oh right, thanks for changing the README next steps!

**Comment by tyxxxx** [comment]
@NaithanB

**Comment by NaithanB** [comment]
Looks good. There's a small bug where making a new post while translating will set the payment period to always display in the translated language. It's easy to fix though. It also impacts the edit post function but it's the same fix. I can do it after we merge.

**Comment by NaithanB** [comment]
Actually, I'll just push the fix to this branch since it's super small (2 lines). I haven't changed the editPost component though because I forgot @BarneyShi changed the setup slightly. Barney, do you want to update that?

**Review by NaithanB — APPROVED** [review]

**Comment by BarneyShi** [comment]
@NaithanB No problem. I will do it.

**Comment by BarneyShi** [comment]
@NaithanB In editPost, I found Yuxin already translated the texts of payment period. It displays correctly as I checked

**Comment by NaithanB** [comment]
@BarneyShi, did you create a new post, go to the post detail page, switch the language, change the payment period, update the post with the new payment period, then check the main page in English? I think if you do that, the payment period wont display in English anymore because the translated text is pushed to the database. That's what happened for me anyway.

**Comment by BarneyShi** [comment]
@NaithanB Oh I see, that's the bug. I will do it later. Thanks for spotting that!

**Comment by tyxxxx** [comment]
@NaithanB @parksj23 @BarneyShi Hi, logging in and out of the account, all posts will be reloaded and loaded for some time. It's a bit of a waste of time, so I optimized the code. Now I won't load posts when I log in or log out at any time, please check that

**Comment by BarneyShi** [comment]
@NaithanB I fixed the payment period text display bugs. It should work normally now.

**Comment by NaithanB** [comment]
Looks good. Shall we merge this?

**Pull request merged**
