### PR TITLE
Update <PostDetail /> component

### PR DESCRIPTION
**Pull request by BarneyShi**
Finished parts:
1. Edit post
2. Comment function, 
3. Delete post
4. Report function 
5. Use a scraper to convert postal code to coordinates

Todos:
1. Need to know current user to finish some details.
2. Need to find a way to edit post images, like removing old ones or adding new ones.
3. Might implement deleting comments function if there is time left.

### CODE REVIEW

**Comment by NaithanB** [comment]
@BarneyShi, This is awesome! Looks really nice. Great idea to include a "view more" button. It's pretty cool having a working map too.

Just a couple possible changes. When you click the view more button, in the modal view that opens, Lease length appears twice. 

Adding those extra loading spinners looks better. I think we should remove the one on the comment box though. It looks a bit like an error to me. Or maybe we could hide the comment box until the page loads?

The delete button isn't doing anything on my end. 

Did anyone take implementing the rating buttons?

**Comment by NaithanB** [comment]
P.S. happy to merge this now. Those changes are really minor.

**Comment by NaithanB** [comment]
Oh, I also noticed, in PostDetail, there was a useEffect I added to get the current post. I added a state to display the schedule that we get from the database rather than the fixed schedule. I think that got removed. Was that intentional? There was also an alert that displayed error messages if the we received bad info, but now if there's a connection problem we get stuck with the loading spinner and the alert is gone.

**Comment by BarneyShi** [comment]
> Oh, I also noticed, in PostDetail, there was a useEffect I added to get the current post. I added a state to display the schedule that we get from the database rather than the fixed schedule. I think that got removed. Was that intentional? There was also an alert that displayed error messages if the we received bad info, but now if there's a connection problem we get stuck with the loading spinner and the alert is gone.

@NaithanB I guess I might accidentally removed them when dealing with conflicts. I will added them back. 
For rating, I finished backend part but I didn't work on the front-end part because we don't know who the current user is. I will make changes based on your comments. Thanks!

**Comment by NaithanB** [comment]
Yeah, that's easy to do. Sounds good. That makes sense about the rating part. Should have looked in the code first.

**Pull request merged**
